### ISSUE TITLE
Incompatibility

### ISSUE THREAD

**Issue by carmas123** [StephenVinouze/AdvancedRecyclerView#1]
Hi, your component aren't compatible with 
com.mcxiaoke.koi:core
com.mcxiaoke.koi:async
please can you check this.

**Comment by StephenVinouze** [comment]
It seems that both our `core` modules are messing with each other probably because they have the same name, leading to duplicated files while merging the apk.

I've googled it but can't find how to prevent it. Any ideas?

Btw if you import only their `async` module there is no conflict with this library.
